# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo

    docker:

      # specify the version you desire here
      - image: circleci/clojure:lein-2.7.1

      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test
          DATABASE_NAME: groove-api
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4


    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: cd groove-api
      - run: |
          psql -localhost \
          $POSTGRES_USER -c \
          "CREATE DATABASE groove-api;"
      - run: |
          psql \
          -h localhost \
          -U $POSTGRES_USER \
          -d $TEST_DATABASE_URL \
          -f 'migrations/create_tables.sql'
      - run: |
          psql \
          -h localhost \
          -U $POSTGRES_USER \
          -d $TEST_DATABASE_URL \
          -c "INSERT INTO public.user VALUES ('e8ms2cu1fese7h8k6fcog@test.no', \
              'e8ms2cu1fese7h8k6fcog@test.no', 'e8ms2cu1fese7h8k6fcog', \
              'bcrypt+sha512$807266fb5c8ec5cc034f6e4798c26dca$12$a35644b9caa3a92c217e35b22ea88b93b767f76b2fe793eb', \
              0,'2f604c4c-4f8f-49ec-88ef-d9e73b0b0815', t);"
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: lein deps

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      # run tests!
      - run: lein test
